[package]
name = "tmsim-converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26" 
serde_json = "1.0.79" 
serde = {version = "1.0.136", features = ["derive"]} 
regex = "1.5.4" 